### ISSUE TITLE
peek and poke need additional argument to prevent printf

### ISSUE THREAD

**Issue by chick** [ucb-bar/chisel#588]
Example: during development in tests there are use cases where you may want to use the result of peek in some calculation, without the printf in peek cluttering up the output.  In a default Tester the isTrace flag is set to true.  It would be nice to have an argument like silent: Bool = false that allows specific programmer to disable the print

**Comment by ucbjrl** [comment]
It turns out some of the peeks are generated internally by the Tester and the simplest way to silence them is by toggling the `isTrace` member variable.

As a new Tester interface is under development for Chisel3, we'd like to hold off adding new features/complexity to the existing Tester interface.
